"""ACS bootstrap values for playbooks: the `acs.*` namespace (doc 42 §9.7).

An OLT step can push the CPE's TR-069 management config over OMCI (doc 42c,
doc 42b `Set ONU ACS`). The four values it needs already exist, and no
playbook author may type them:

    acs.url              provisioning_settings.acs_base_url, else env
                         GENIEACS_CWMP_PUBLIC_URL (what Settings -> Red shows)
    acs.inform_password  decrypt of provisioning_settings.cwmp_credential_id
    acs.cr_username      random per child, generated by backend-erp's worker
    acs.cr_password      in memory and discarded (founder round 4: the ACS
                         cannot reach a CPE's connection-request URL, so the
                         pair is never stored and nothing here mints it)

`create_run` checks url + inform password (and ensures the CPE's registration,
which tags the device in the ACS) before any child exists; backend-erp's
worker loads them again at claim and merges them into the job's variables IN
MEMORY only, never into job.variables, frames or logs.

ponytail: only the CPE's own registration is ensured, and only when a
playbook reads `acs.*`; bulk pre-registration stays POST /acs/registrations/bulk.
"""
from __future__ import annotations

import json
import os
import re
import uuid
from collections.abc import Iterable
from typing import Any

from sqlalchemy.orm import Session

from database_utils.models.isp import AcsDeviceRegistration, DeviceCredential
from database_utils.schemas.acs_registration import _normalize_serial
from database_utils.utils import crypto
from database_utils.utils.provisioning_resolution import ResolutionError
from database_utils.utils.transport import company_provisioning_settings

ENV_CWMP_PUBLIC_URL = "GENIEACS_CWMP_PUBLIC_URL"
ACS_KEYS = ("url", "inform_password", "cr_username", "cr_password")
ACS_TOKEN = re.compile(r"\{\{\s*acs\.")
# The capture charset (doc 42 §4.3): a space or a quote would split the
# OLT command line.
ACS_VALUE_SAFE = re.compile(r"[A-Za-z0-9_.:/+-]{1,128}")

ACS_NOT_CONFIGURED = "ACS_NOT_CONFIGURED"
ACS_VALUE_UNSAFE = "ACS_VALUE_UNSAFE"
ACS_SERIAL_CLAIMED = "ACS_SERIAL_CLAIMED"


def reads_acs(definitions: Iterable[Any]) -> bool:
    """True when any of these (definition / step list) dicts holds an {{acs.*}} token."""
    return any(ACS_TOKEN.search(json.dumps(d, default=str)) for d in definitions)


def acs_url(settings) -> str | None:
    """The CWMP URL a CPE must inform: the tenant row's acs_base_url when set,
    else the platform env (Backend and ProvisionWorker both carry it)."""
    url = (getattr(settings, "acs_base_url", None) or os.getenv(ENV_CWMP_PUBLIC_URL) or "").strip()
    return url or None


def _refuse(code: str, detail: str):
    raise ResolutionError(code, detail)


def _inform_password(db: Session, company_id, settings) -> str | None:
    cred_id = getattr(settings, "cwmp_credential_id", None)
    cred = db.get(DeviceCredential, cred_id) if cred_id else None
    if cred is None or cred.company_id != company_id:
        return None
    try:
        return crypto.decrypt_secret(cred.secret_ciphertext, cred.dek_wrapped,
                                     cred.kek_id, company_id, cred.id)
    except crypto.CredentialCryptoError:
        return None


def _registration(db: Session, company_id, serial: str, *, item_id=None,
                  ensure: bool = False) -> AcsDeviceRegistration | None:
    """This tenant's registration of the serial (any OUI), created when
    `ensure`. A row owned by another tenant, or quarantined (company NULL,
    awaiting superadmin assignment), refuses: the same rule as
    POST /acs/registrations' 409."""
    rows = (db.query(AcsDeviceRegistration)
            .filter(AcsDeviceRegistration.serial_number == serial)
            .order_by(AcsDeviceRegistration.created_at, AcsDeviceRegistration.id)
            .all())
    if any(r.company_id != company_id for r in rows):
        _refuse(ACS_SERIAL_CLAIMED,
                f"The CPE serial {serial} is registered in the ACS outside this company "
                "(another tenant or quarantine)")
    if rows:
        reg = rows[0]
    elif ensure:
        reg = AcsDeviceRegistration(id=uuid.uuid4(), company_id=company_id, serial_number=serial)
        db.add(reg)
    else:
        return None
    if ensure and reg.inventory_item_id is None and item_id is not None:
        reg.inventory_item_id = item_id
    return reg


def acs_values(db: Session, company_id, serial: str | None, *, item_id=None,
               ensure: bool = False) -> dict[str, str]:
    """{url, inform_password} for the CPE `serial` of `company_id`. Callers
    must never log or persist the result.

    ensure=True (create_run, non-dry) creates the tenant's registration of the
    serial when absent and stamps the inventory item; ensure=False
    (preflight, dry run, the worker) writes nothing.

    Raises ResolutionError ACS_NOT_CONFIGURED (no URL, no / unreadable inform
    credential, no CPE serial), ACS_SERIAL_CLAIMED, or ACS_VALUE_UNSAFE (a
    value outside [A-Za-z0-9_.:/+-]{1,128})."""
    settings = company_provisioning_settings(db, company_id)
    url = acs_url(settings)
    if url is None:
        _refuse(ACS_NOT_CONFIGURED, "No ACS URL: set GENIEACS_CWMP_PUBLIC_URL (or the tenant's ACS URL)")
    password = _inform_password(db, company_id, settings)
    if password is None:
        _refuse(ACS_NOT_CONFIGURED,
                "No readable TR-069 inform password: generate it in Configuración → Red")
    values = {"url": url, "inform_password": password}
    for key, value in values.items():
        if not ACS_VALUE_SAFE.fullmatch(value):
            _refuse(ACS_VALUE_UNSAFE, f"acs.{key} has characters an OLT command cannot carry")
    serial = _normalize_serial(serial or "")
    if not serial:
        _refuse(ACS_NOT_CONFIGURED, "The service's CPE has no serial number to register in the ACS")
    _registration(db, company_id, serial, item_id=item_id, ensure=ensure)
    return values
